#!/usr/bin/env python3

# -*- coding: utf-8 -*-
"""
@author: alexogilvie

Project Euler Problem 45: Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
import time
def compute():
    timer = time.time()
    i = 286
    j = 166
    k = 144
    while True:
        triangle = i * (i + 1) // 2
        pentagon = j * (j * 3 - 1) // 2
        hexagon  = k * (k * 2 - 1)
        minimum = min(triangle, pentagon, hexagon)
        if minimum == max(triangle, pentagon, hexagon):
            ans = triangle
            break
        if minimum == triangle: i += 1
        if minimum == pentagon: j += 1
        if minimum == hexagon : k += 1
    print ("Answer is " + str(ans) + ". Completed in "+str(time.time()-timer)+" seconds.")
    return ans